### ISSUE TITLE
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

### ISSUE THREAD

**Issue by femueller** [zalando-stups/zign#9]
Apparently there is a bug in the latest version of the keyring python module, which is used by zign.
This leads to a problem, that in [Taupage](https://github.com/zalando-stups/taupage) during boot a script, which uses zign tries to open the dbus-daemon.

```
Traceback (most recent call last):
  File "./init.d/03-push-taupage-yaml.py", line 10, in <module>
    from taupage import configure_logging, get_config, mask_dictionary, get_token, get_boot_time
  File "/usr/local/lib/python3.4/dist-packages/taupage/__init__.py", line 11, in <module>
    import zign.api
  File "/usr/local/lib/python3.4/dist-packages/zign/api.py", line 3, in <module>
    import keyring
  File "/usr/local/lib/python3.4/dist-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python3.4/dist-packages/keyring/core.py", line 158, in <module>
    init_backend()
  File "/usr/local/lib/python3.4/dist-packages/keyring/core.py", line 58, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/usr/local/lib/python3.4/dist-packages/keyring/core.py", line 66, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/usr/local/lib/python3.4/dist-packages/keyring/util/__init__.py", line 20, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/keyring/backend.py", line 180, in get_all_keyring
    exceptions=TypeError))
  File "/usr/local/lib/python3.4/dist-packages/keyring/util/__init__.py", line 29, in suppress_exceptions
    for callable in callables:
  File "/usr/local/lib/python3.4/dist-packages/keyring/backend.py", line 172, in is_class_viable
    keyring_cls.priority
  File "/usr/local/lib/python3.4/dist-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/local/lib/python3.4/dist-packages/keyring/util/XDG.py", line 18, in wrapper
    return func(*args, **kwargs) * self.multiplier
  File "/usr/local/lib/python3.4/dist-packages/keyring/backends/kwallet.py", line 134, in priority
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

**Comment by femueller** [comment]
Since this has been fixed in https://github.com/jaraco/keyring/pull/182 it can be closed.
